rootProject.name = "hugg"
include(":app")
include(":domain")
include(":feature")
include(":data")
include(":feature:main")
include(":feature:sign")
include(":feature:calendar")
include(":feature:account")
include(":feature:dailyHugg")
include(":feature:myPage")
include(":feature:home")
include(":feature:challenge")
include(":feature:challenge:list")
